<a href="https://colab.research.google.com/github/samarkumar4355/Data_Science/blob/main/class_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
# pandas


import pandas as pd

dict = {
    'name': ['a','b','c','d'],
    'age' : [20,21,22,23],
    'roll': [1,2,3,4]
}

df = pd.DataFrame(dict)
df1 = pd.DataFrame(dict, index=['a','b', 'c','d'])

# df

display(df)
display(df1)

  name  age  roll
0    a   20     1
1    b   21     2
2    c   22     3
3    d   23     4

  name  age  roll
a    a   20     1
b    b   21     2
c    c   22     3
d    d   23     4

In [14]:
df = pd.read_csv('student_data.csv')

df.head() # gives data from start, by default 5

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [16]:
df = pd.read_csv('student_data.csv')

df.tail() # gives data from end, by default 5

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [17]:
df = pd.read_csv('student_data.csv')
df.shape # gives number of rows and column of data

(10000, 8)

In [22]:
df = pd.read_csv('student_data.csv')
df.info() # gives metadata about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

In [104]:
df = pd.read_csv('student_data.csv')

df.describe()

# three types of quartile = q1, q2, q3
# q1= 25%, q2= 50%, q3 = 75%
# q1 = 1st de median tk ka median
# median is also called q2
#q2 = median de last tk ka median

# IQR = q3-q1   # inter quartile range

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [103]:
df = pd.read_csv('student_data.csv')

df.columns    # gives name  of all the columns

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

In [102]:
df = pd.read_csv('student_data.csv')
df.index     #gives info about indexing

RangeIndex(start=0, stop=10000, step=1)

In [101]:
df = pd.read_csv('student_data.csv')
df['internet_usage']   #gives data of any specific column

0        7
1        3
2        6
3        8
4        6
        ..
9995     7
9996     9
9997     5
9998     5
9999    11
Name: internet_usage, Length: 10000, dtype: int64

In [100]:
df = pd.read_csv('student_data.csv')
df[['internet_usage', 'study_hours']]   #gives data of any specific columns

      internet_usage  study_hours
0                  7            7
1                  3            4
2                  6           11
3                  8            8
4                  6            5
...              ...          ...
9995               7            2
9996               9            7
9997               5           10
9998               5           10
9999              11            2

[10000 rows x 2 columns]

In [99]:
df = pd.read_csv('student_data.csv')
df.iloc[0]  #gives data of any specific row

study_hours                   7
attendance                   56
sleep_hours                   8
internet_usage                7
assignments_completed        10
previous_score               62
exam_score                100.0
placement_status         Placed
Name: 0, dtype: object

In [98]:
df = pd.read_csv('student_data.csv')
df.iloc[0:5]  #gives data from 0th row to 4th row

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [97]:
df = pd.read_csv('student_data.csv')

df.loc[df['study_hours'] == 11]   #jiski bhi study hours 11 hrs hai uski details de deag ye

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
2,11,60,7,6,10,45,100.00,Placed
9,11,77,4,9,15,69,100.00,Placed
10,11,64,8,8,12,76,100.00,Placed
29,11,63,9,10,1,72,96.59,Placed
30,11,45,5,2,4,93,100.00,Placed
...,...,...,...,...,...,...,...,...
9969,11,84,8,2,3,83,100.00,Placed
9971,11,81,9,6,0,85,100.00,Placed
9978,11,92,8,2,16,79,100.00,Placed
9979,11,78,9,5,18,82,100.00,Placed
9988,11,94,6,9,6,67,100.00,Placed

In [96]:
df = pd.read_csv('student_data.csv')

df2 = df.loc[df['study_hours'] == 11]
df2[['study_hours','sleep_hours']]

#iloc works on index only, e.g iloc[0] it will work
#loc works on labels , e.g. loc[0] ->error, it will work with loc[a] here a is label

      study_hours  sleep_hours
2              11            7
9              11            4
10             11            8
29             11            9
30             11            5
...           ...          ...
9969           11            8
9971           11            9
9978           11            8
9979           11            9
9988           11            6

[868 rows x 2 columns]

In [49]:
df = pd.read_csv('student_data.csv')

df2 = df.loc[df['study_hours'] == 11]
df.loc[4]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [46]:
df = pd.read_csv('student_data.csv')

df.loc[df['study_hours'] == 11, ['sleep_hours','study_hours']]
#jiski bhi study hours 11 hi uski details dega, but next list me study hours bhi pass krni padegi print ke liye,
# df['study_hours'] == 11, this is the condition jiske according data milege

      sleep_hours  study_hours
2               7           11
9               4           11
10              8           11
29              9           11
30              5           11
...           ...          ...
9969            8           11
9971            9           11
9978            8           11
9979            9           11
9988            6           11

[868 rows x 2 columns]

In [95]:
df = pd.read_csv('student_data.csv')

df.loc[df['study_hours'] == 11, ['sleep_hours','study_hours']].iloc[4:8] # ye row 4 se 8 th ka hi data dega

     sleep_hours  study_hours
30             5           11
91             9           11
98             6           11
116            7           11

In [51]:
import pandas as pd
df = pd.read_csv('student_data.csv')

df.loc[df['study_hours'] == 11, ['sleep_hours','study_hours']]

      sleep_hours  study_hours
2               7           11
9               4           11
10              8           11
29              9           11
30              5           11
...           ...          ...
9969            8           11
9971            9           11
9978            8           11
9979            9           11
9988            6           11

[868 rows x 2 columns]

In [93]:


df = pd.read_csv("student_data.csv")
df.loc[df['assignments_completed']==8].iloc[1:2]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
4,5,52,8,6,8,40,78.82,Placed

In [74]:

df = pd.read_csv('student_data.csv')

df[df["assignments_completed"] > 3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [94]:
df = pd.read_csv('student_data.csv')

df["age"] = 20 # this will add a new column to the data

df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [105]:
df = pd.read_csv('student_data.csv')

#reanme function

df.rename(columns = {'assignments_completed':'assign_completed'},inplace = True) # inplace true use krne se usi data me change krta h but if not used then it will create a new data
df

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [111]:
#remove rows or columns
# row =0, column = 1
df = pd.read_csv('student_data.csv')

# df.drop("study_hours", axis=1, inplace=True)
df.drop("study_hours", axis=1, inplace=True)
df.drop(1, axis=0, inplace=True)

df

,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,56,8,7,10,62,100.00,Placed
2,60,7,6,10,45,100.00,Placed
3,99,9,8,4,55,90.17,Placed
4,52,8,6,8,40,78.82,Placed
5,40,9,10,0,60,72.33,Placed
...,...,...,...,...,...,...,...
9995,58,9,7,8,88,69.31,Not Placed
9996,98,6,9,4,87,100.00,Placed
9997,44,8,5,10,37,95.94,Placed
9998,75,7,5,8,52,88.61,Placed
9999,70,6,11,16,52,78.96,Placed

In [121]:
#remove missing values

dct = {
    'name' :['a', 'b', 'c', 'd'],
    'age' :[20, None, 22, None],
    'roll' :[1, None, 3, None]
}

df = pd.DataFrame(dct)


df = df.dropna()  # it works for the null values, null means none, ye uss row ko hi hta dega
df = df.dropna()
df

  name   age  roll
0    a  20.0   1.0
2    c  22.0   3.0

In [ ]:
# Sort values by column
df = pd.read_csv('student_data.csv')

df.sort_values()

In [117]:
df = pd.read_csv('student_data.csv')

df.isnull() # check for non-missing values

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False

In [ ]:
df = pd.read_csv('student_data.csv')

df.notnull()

In [125]:
dct = {
    'name' :['a', 'b', 'c', 'd'],
    'age' :[20, 0, 22, 0],
    'roll' :[1, 0, 3, 0]
}

df.fillna(0, inplace=True)
df

  name   age  roll
0    a  20.0   1.0
2    c  22.0   3.0